# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice_agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11voice_agent.proto\"\x07\n\x05\x45mpty\"%\n\x10WakeWordDetected\x12\x11\n\twake_word\x18\x01 \x01(\x08\"J\n\x0c\x41gentControl\x12\x1c\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0c.AgentAction\x12\x1c\n\tnlu_model\x18\x02 \x01(\x0e\x32\t.NLUModel\")\n\nIntentSlot\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"[\n\x0b\x41gentResult\x12\x14\n\x0cuser_command\x18\x01 \x01(\t\x12\x13\n\x0buser_intent\x18\x02 \x01(\t\x12!\n\x0cintent_slots\x18\x03 \x03(\x0b\x32\x0b.IntentSlot*\"\n\x0b\x41gentAction\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01*\x1f\n\x08NLUModel\x12\t\n\x05SNIPS\x10\x00\x12\x08\n\x04RASA\x10\x01\x32n\n\x11VoiceAgentService\x12.\n\x0fWaitForWakeWord\x12\x06.Empty\x1a\x11.WakeWordDetected0\x01\x12)\n\nVoiceAgent\x12\r.AgentControl\x1a\x0c.AgentResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AGENTACTION']._serialized_start=281
  _globals['_AGENTACTION']._serialized_end=315
  _globals['_NLUMODEL']._serialized_start=317
  _globals['_NLUMODEL']._serialized_end=348
  _globals['_EMPTY']._serialized_start=21
  _globals['_EMPTY']._serialized_end=28
  _globals['_WAKEWORDDETECTED']._serialized_start=30
  _globals['_WAKEWORDDETECTED']._serialized_end=67
  _globals['_AGENTCONTROL']._serialized_start=69
  _globals['_AGENTCONTROL']._serialized_end=143
  _globals['_INTENTSLOT']._serialized_start=145
  _globals['_INTENTSLOT']._serialized_end=186
  _globals['_AGENTRESULT']._serialized_start=188
  _globals['_AGENTRESULT']._serialized_end=279
  _globals['_VOICEAGENTSERVICE']._serialized_start=350
  _globals['_VOICEAGENTSERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
