# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import voice_agent_pb2 as voice__agent__pb2


class VoiceAgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WaitForWakeWord = channel.unary_stream(
                '/VoiceAgentService/WaitForWakeWord',
                request_serializer=voice__agent__pb2.Empty.SerializeToString,
                response_deserializer=voice__agent__pb2.WakeWordDetected.FromString,
                )
        self.VoiceAgent = channel.unary_unary(
                '/VoiceAgentService/VoiceAgent',
                request_serializer=voice__agent__pb2.AgentControl.SerializeToString,
                response_deserializer=voice__agent__pb2.AgentResult.FromString,
                )


class VoiceAgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WaitForWakeWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoiceAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WaitForWakeWord': grpc.unary_stream_rpc_method_handler(
                    servicer.WaitForWakeWord,
                    request_deserializer=voice__agent__pb2.Empty.FromString,
                    response_serializer=voice__agent__pb2.WakeWordDetected.SerializeToString,
            ),
            'VoiceAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.VoiceAgent,
                    request_deserializer=voice__agent__pb2.AgentControl.FromString,
                    response_serializer=voice__agent__pb2.AgentResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VoiceAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoiceAgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WaitForWakeWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/VoiceAgentService/WaitForWakeWord',
            voice__agent__pb2.Empty.SerializeToString,
            voice__agent__pb2.WakeWordDetected.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VoiceAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VoiceAgentService/VoiceAgent',
            voice__agent__pb2.AgentControl.SerializeToString,
            voice__agent__pb2.AgentResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
